import {test} from 'node:test'
import assert from 'node:assert/strict'
import {interimRef,sweepBudget,validateInterimLedger,validateInterimMint,INTERIM_DESK,MINT_IFACE,type InterimDeposit} from './wrap-interim-policy.js'
import {pendingV2Zats} from './wrap-v2-policy.js'
const d:InterimDeposit={routeId:0,recipient:'0x1C083F2f85aCadae452C7512C45cD7c8a3ddbF03',address:'t1RtmsoPs9d9SZpXKmJJpDH3g6qNmBegN98',txid:'0x'+'ab'.repeat(32),index:0,amountZats:'107001',state:'observed'}
test('different native outputs never share an interim reference',()=>{assert.notEqual(interimRef(d.txid,0),interimRef(d.txid,1));assert.equal(interimRef(d.txid.toUpperCase().replace('0X','0x'),0),interimRef(d.txid,0));assert.throws(()=>interimRef(d.txid,-1))})
test('bridge actual amount is owed in full; fee requires separate project margin',()=>{assert.equal(pendingV2Zats([d]),107001n);assert.deepEqual(sweepBudget(d,10000n),{gross:107001n,net:97001n,fee:10000n});assert.throws(()=>sweepBudget(d,9999n));assert.throws(()=>sweepBudget({...d,state:'sweep-signed'},10000n))})
test('missing, duplicated and incomplete signed ledgers fail closed',()=>{assert.throws(()=>validateInterimLedger({}));assert.throws(()=>validateInterimLedger({version:1,deposits:[d,d]}));assert.throws(()=>validateInterimLedger({version:1,deposits:[{...d,state:'minted'}]}));assert.equal(validateInterimLedger({version:1,deposits:[d]}).deposits.length,1)})
test('receipt must bind exact recipient, actual amount, reference and minter desk',()=>{const args=[d.recipient,107001n,interimRef(d.txid,0)];const data=MINT_IFACE.encodeFunctionData('operatorMint',args);const event=MINT_IFACE.encodeEventLog(MINT_IFACE.getEvent('ReserveMint')!,args);const logs=[{address:INTERIM_DESK,...event}];validateInterimMint(d,{to:INTERIM_DESK,data},logs);assert.throws(()=>validateInterimMint({...d,amountZats:'100001'},{to:INTERIM_DESK,data},logs));assert.throws(()=>validateInterimMint(d,{to:d.recipient,data},logs));assert.throws(()=>validateInterimMint(d,{to:INTERIM_DESK,data},[]))})
